// Malaysian-specific default categories with tax implications

export const defaultCategories = [
  // Income Categories
  {
    name: "Salary",
    color: "#10B981",
    icon: "💼",
    type: "income",
    isTaxDeductible: false,
    isSystem: true,
  },
  {
    name: "Freelance/Business",
    color: "#059669",
    icon: "💻",
    type: "income",
    isTaxDeductible: false,
    isSystem: true,
  },
  {
    name: "Investment Returns",
    color: "#34D399",
    icon: "📈",
    type: "income",
    isTaxDeductible: false,
    isSystem: true,
  },
  {
    name: "Other Income",
    color: "#6EE7B7",
    icon: "💰",
    type: "income",
    isTaxDeductible: false,
    isSystem: true,
  },

  // Expense Categories - Tax Deductible (Medical & Insurance)
  {
    name: "Medical Insurance",
    color: "#EF4444",
    icon: "🏥",
    type: "expense",
    isTaxDeductible: true,
    taxCategory: "medical_insurance",
    isSystem: true,
  },
  {
    name: "Education Insurance",
    color: "#DC2626",
    icon: "🎓",
    type: "expense",
    isTaxDeductible: true,
    taxCategory: "education_insurance",
    isSystem: true,
  },
  {
    name: "Medical Expenses",
    color: "#F87171",
    icon: "💊",
    type: "expense",
    isTaxDeductible: true,
    taxCategory: "self_medical",
    isSystem: true,
  },
  {
    name: "Parents Medical",
    color: "#FCA5A5",
    icon: "👨‍👩‍👧‍👦",
    type: "expense",
    isTaxDeductible: true,
    taxCategory: "parents_medical",
    isSystem: true,
  },

  // Education (Tax Deductible)
  {
    name: "Education Fees",
    color: "#3B82F6",
    icon: "📚",
    type: "expense",
    isTaxDeductible: true,
    taxCategory: "education_fees",
    isSystem: true,
  },
  {
    name: "Skill Development",
    color: "#60A5FA",
    icon: "🎯",
    type: "expense",
    isTaxDeductible: true,
    taxCategory: "skill_development",
    isSystem: true,
  },
  {
    name: "SSPN Savings",
    color: "#93C5FD",
    icon: "🏦",
    type: "expense",
    isTaxDeductible: true,
    taxCategory: "sspn",
    isSystem: true,
  },

  // Lifestyle (Tax Deductible up to RM 2,500)
  {
    name: "Books & Journals",
    color: "#8B5CF6",
    icon: "📖",
    type: "expense",
    isTaxDeductible: true,
    taxCategory: "lifestyle",
    isSystem: true,
  },
  {
    name: "Tech & Gadgets",
    color: "#A78BFA",
    icon: "💻",
    type: "expense",
    isTaxDeductible: true,
    taxCategory: "lifestyle",
    isSystem: true,
  },
  {
    name: "Internet & Phone",
    color: "#C4B5FD",
    icon: "📱",
    type: "expense",
    isTaxDeductible: true,
    taxCategory: "lifestyle",
    isSystem: true,
  },
  {
    name: "Sports Equipment",
    color: "#DDD6FE",
    icon: "⚽",
    type: "expense",
    isTaxDeductible: true,
    taxCategory: "lifestyle",
    isSystem: true,
  },

  // EPF (Tax Deductible)
  {
    name: "EPF Contribution",
    color: "#14B8A6",
    icon: "🏦",
    type: "expense",
    isTaxDeductible: true,
    taxCategory: "epf",
    isSystem: true,
  },

  // Regular Expenses (Non-deductible)
  {
    name: "Food & Dining",
    color: "#F59E0B",
    icon: "🍔",
    type: "expense",
    isTaxDeductible: false,
    isSystem: true,
  },
  {
    name: "Groceries",
    color: "#FBBF24",
    icon: "🛒",
    type: "expense",
    isTaxDeductible: false,
    isSystem: true,
  },
  {
    name: "Transportation",
    color: "#6366F1",
    icon: "🚗",
    type: "expense",
    isTaxDeductible: false,
    isSystem: true,
  },
  {
    name: "Petrol & Toll",
    color: "#818CF8",
    icon: "⛽",
    type: "expense",
    isTaxDeductible: false,
    isSystem: true,
  },
  {
    name: "Grab & Transport",
    color: "#A5B4FC",
    icon: "🚕",
    type: "expense",
    isTaxDeductible: false,
    isSystem: true,
  },
  {
    name: "Utilities",
    color: "#EC4899",
    icon: "💡",
    type: "expense",
    isTaxDeductible: false,
    isSystem: true,
  },
  {
    name: "Rent & Housing",
    color: "#F472B6",
    icon: "🏠",
    type: "expense",
    isTaxDeductible: false,
    isSystem: true,
  },
  {
    name: "Entertainment",
    color: "#FB923C",
    icon: "🎬",
    type: "expense",
    isTaxDeductible: false,
    isSystem: true,
  },
  {
    name: "Shopping",
    color: "#FDBA74",
    icon: "🛍️",
    type: "expense",
    isTaxDeductible: false,
    isSystem: true,
  },
  {
    name: "Shopee/Lazada",
    color: "#FED7AA",
    icon: "📦",
    type: "expense",
    isTaxDeductible: false,
    isSystem: true,
  },
  {
    name: "Personal Care",
    color: "#A855F7",
    icon: "💅",
    type: "expense",
    isTaxDeductible: false,
    isSystem: true,
  },
  {
    name: "Fitness & Gym",
    color: "#C084FC",
    icon: "💪",
    type: "expense",
    isTaxDeductible: false,
    isSystem: true,
  },
  {
    name: "Travel",
    color: "#22D3EE",
    icon: "✈️",
    type: "expense",
    isTaxDeductible: false,
    isSystem: true,
  },
  {
    name: "Gifts & Donations",
    color: "#67E8F9",
    icon: "🎁",
    type: "expense",
    isTaxDeductible: false,
    isSystem: true,
  },
  {
    name: "Subscriptions",
    color: "#A3E635",
    icon: "📺",
    type: "expense",
    isTaxDeductible: false,
    isSystem: true,
  },
  {
    name: "Other Expenses",
    color: "#94A3B8",
    icon: "📋",
    type: "expense",
    isTaxDeductible: false,
    isSystem: true,
  },
];

// LHDN Tax Relief Categories with limits for YA 2024
export const taxReliefCategories = {
  basic_personal_relief: {
    name: "Basic Personal Relief",
    maxAmount: 9000,
    description: "Automatic relief for all taxpayers",
  },
  medical_insurance: {
    name: "Medical & Education Insurance Premiums",
    maxAmount: 3000,
    description: "Self, spouse, and children",
  },
  self_medical: {
    name: "Self & Spouse Medical Expenses",
    maxAmount: 8000,
    description: "Including serious diseases",
  },
  parents_medical: {
    name: "Parents Medical Expenses",
    maxAmount: 8000,
    description: "Medical treatment for parents",
  },
  education_fees: {
    name: "Tertiary/Postgraduate Education Fees",
    maxAmount: 7000,
    description: "Self in Malaysia",
  },
  skill_development: {
    name: "Skill Development Courses",
    maxAmount: 2000,
    description: "Approved skill courses",
  },
  sspn: {
    name: "National Education Savings Scheme (SSPN)",
    maxAmount: 8000,
    description: "Net deposit into SSPN account",
  },
  lifestyle: {
    name: "Lifestyle",
    maxAmount: 2500,
    description: "Books, computers, smartphones, internet, gym, sports equipment",
  },
  epf: {
    name: "Additional EPF Contribution",
    maxAmount: 4000,
    description: "Voluntary EPF contributions",
  },
  breastfeeding_equipment: {
    name: "Breastfeeding Equipment",
    maxAmount: 1000,
    description: "Purchase of breastfeeding equipment",
  },
  ev_charging: {
    name: "EV Charging Facilities",
    maxAmount: null,
    description: "Electric vehicle charging facilities (YA 2025-2027)",
  },
  composting_machine: {
    name: "Food Waste Composting Machine",
    maxAmount: null,
    description: "Purchase of composting machine (YA 2025-2027)",
  },
};

// Popular Malaysian subscription services
export const popularSubscriptions = [
  { name: "Netflix", icon: "🎬", category: "Entertainment" },
  { name: "Disney+ Hotstar", icon: "🎥", category: "Entertainment" },
  { name: "Spotify", icon: "🎵", category: "Entertainment" },
  { name: "YouTube Premium", icon: "▶️", category: "Entertainment" },
  { name: "Amazon Prime", icon: "📦", category: "Shopping" },
  { name: "Shopee Premium", icon: "🛒", category: "Shopping" },
  { name: "Grab Unlimited", icon: "🚕", category: "Transportation" },
  { name: "Touch 'n Go eWallet", icon: "💳", category: "Finance" },
  { name: "Boost", icon: "📱", category: "Finance" },
  { name: "Digi/Maxis/Celcom", icon: "📞", category: "Utilities" },
  { name: "Astro", icon: "📺", category: "Entertainment" },
  { name: "iCloud Storage", icon: "☁️", category: "Technology" },
  { name: "Google One", icon: "☁️", category: "Technology" },
  { name: "Microsoft 365", icon: "💼", category: "Productivity" },
  { name: "Adobe Creative Cloud", icon: "🎨", category: "Productivity" },
  { name: "Fitness First/Celebrity Fitness", icon: "💪", category: "Health & Fitness" },
];
